* PROMICE AWS Data Issue

Automatic weather station (AWS) data from the Greenland Ice Sheet are often imperfect due to the complexity and conditions involved in installing and maintaining the AWS.

This goal of this project is to provide a public space to document and solve issues with [[https://www.promice.org/][PROMICE]] AWS data.

** Issue Labels

*** Time
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/ALL_TIME 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2012 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2013 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2014 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2015 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2016 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2017 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2018 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2019 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2020 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2021 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2022 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2023 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2024 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/2025

*** Station
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/ALL_STATION 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/CEN
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/EGP
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/KAN_U
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/KPC_Uv3
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/NAE
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/NAU

https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/NSE
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/NUK_K
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/NUK_L
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/Roof_GEUS
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/TAS_A
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/UPE_L 
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/UPE_U

*** Sensor

https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/ALL_SENSOR
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/WindDirection
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/WindSpeed
[[https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/SR50%20-%20boom]] 
[[https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/SR50%20-%20stakes]]


** Workflow

+  If you are using PROMICE AWS data and something seems amiss, you can search the [[https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/issues][issues]] to see if someone else has documented the issue.
  + Issues can be searched using [[https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels][labels]] and filtered by Station Name, Year, or Sensor
  + Click in the search box to add additional label filters
  
+ Once an issue has been submitted, a PROMICE scientist will examine and add the https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/CONFIRMED label.

+ If an issue can be solved, a solution will be added to the issue and the https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/SOLUTION label will be added, otherwise https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/labels/NO_SOLUTION.
